/// This peer interface provides access to messaging peer identification.
interface peer {
    use types.{message, error};

    /// Messaging peer identifier.
    type peer-id = string;

    /// Get the list of known `peer-id` that subscribed to given topic.
    /// MAY be an empty list for messaging services without peer identification.
    /// MAY be a partial list of discovered `peer-id` in peer-to-peer messaging.
    list-subscribers(topic: string): result<list<peer-id>, error>;
}
