/// This inferface provides request-reply messaging pattern.
interface request-reply {
    use types.{message, error};

    /// Options for a request operation.
    record request-options {
        /// The maximum amount of time to wait for a response. If the timeout value is 0, then
        /// the request/reply operation will block until a message is received in response.
        timeout-ms: u32,
        /// The maximum number of replies to expect before returning. If this number and timeout are
        /// both 0, then the operation will block until a message is received in response.
        expected-replies: u32
    }

    /// Performs a blocking request operation with an optional set of request options.
    /// This returns all replies received up until timeout or the configured set of expected replies.
    request: func(msg: message, options: option<request-options>) -> result<list<message>, error>;

    /// Sends a reply message for given request.
    reply: func(request: message, reply: message) -> result<_, error>;
}
