interface types {
    /// Errors that can occur when using the messaging interface. 
    variant error {
        /// The operation timed out
        timeout,
        /// An error occurred with the connection
        connection(string),
        /// A permission error occurred
        permission-denied(string),
        /// A catch all for other types of errors
        other(string),
    }

    /// A message topic.
    type topic = string;

    /// List of metadata attached to a message.
    type metadata = list<tuple<string, string>>;

    /// A message with a binary payload and additional information
    resource message {
        constructor(data: list<u8>);
        /// The topic/subject/channel this message was received on, if any
        topic: func() -> option<topic>;
        /// The content type describing the format of the data in the message
        content-type: func() -> option<string>;
        /// Sets the content type describing the format of the data in the message
        set-content-type: func(content-type: string);
        /// An opaque blob of data
        data: func() -> list<u8>;
        /// Sets the opaque blob of data for this message
        set-data: func(data: list<u8>);
        /// Metadata (aka headers or attributes) attached to the message
        metadata: func() -> option<metadata>;
        /// Adds a new key-value pair to the metadata, overwriting any existing value for the same key
        add-metadata: func(key: string, value: string);
        /// Sets the metadata
        set-metadata: func(data: metadata);
        /// Removes a key-value pair from the metadata
        remove-metadata: func(key: string);
    }
}
