interface types {
    /// Errors that can occur when using the messaging interface. 
    variant error {
        /// The operation timed out
        timeout,
        /// An error occurred with the connection
        connection(string),
        /// A permission error occurred
        permission-denied(string),
        /// A catch all for other types of errors
        other(string),
        /// The operation is unsupported
        unsupported,
    }

    /// A message topic.
    type topic = string;

    /// List of metadata attached to a message.
    type metadata = list<tuple<string, string>>;

    /// A message with a binary payload and additional information
    record message {
        /// The topic/subject/channel this message was received or should be sent on
        topic: topic,
        /// The content type describing the format of the data in the message.
        content-type: option<string>,
        /// An opaque blob of data
        data: list<u8>,
        /// Metadata (aka headers or attributes) attached to the message
        metadata: metadata
    }
}
