package mithic:messaging@0.2.0;

/// Provides message sending and request/reply APIs.
world imports {
	import producer;
	import request-reply;
	import presence;
}

/// Enables component to handle incoming messages with messaging and request/reply capabilities.
world messaging {
	include imports;
	export incoming-handler;
}
