/// The inferface exposes a root for virtual DOM rendering.
interface root {
    use types.{element, element-id, element-patch, event};

    /// Creates a root with the specified identifier.
    create: func(identifier: string) -> option<root>;

    /// Root for virtual DOM rendering.
    resource root {
        /// Render a full virtual DOM element tree given by list of elements and the root element ID.
        render: func(elements: list<element>, root: element-id);

        /// Update and re-render the DOM with given patches. Has no effect if root has never been rendered before.
        update: func(patches: list<element-patch>);

        /// Read and pop all DOM events in queue. Event subscription is specified through onX flags on element props.
        read-events: func() -> list<event>;
    }
}
