[build]
target = "wasm32-wasip2"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-args=-z stack-size=65536"
]

[target.wasm32-wasip2]
rustflags = [
  "-C", "link-args=-z stack-size=65536"
]
