name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci --ignore-scripts
    - run: npm run build
    - run: npm test
      env:
        CI: true
    - uses: codecov/codecov-action@v3
