name: build
on:
  push:
    branches: [main, wasm]
  pull_request:
    branches: [main, wasm]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '26'
    - run: rustup target add wasm32-wasip2
    - run: npm ci
    - run: npm run build
    - run: npm run typecheck
    - run: npx playwright install --with-deps
    - run: npm test
    - run: npm run test:node-native
    - uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
