name: pages
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  build_gh_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '26'
    - run: rustup target add wasm32-wasip2
    - run: npm ci --ignore-scripts
    - run: npm run build
    - run: npm run doc
    - run: mkdir -p ./public && cp -r ./docs/api ./packages/examples/shell/dist/ ./public
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
