name: pages
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  build_gh_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci --ignore-scripts
    - run: npm run doc
    - run: cp -r ./docs ./public
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
